services:
  - type: web
    name: dove-church
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        value: "mongodb+srv://dove_admin:kQt3f0wk2abekE5x@cluster1.xxt8zzi.mongodb.net/test?appName=Cluster1"
      - key: JWT_SECRET
        value: "dove-church-jwt-secret-2024"
      - key: JWT_EXPIRES_IN
        value: "7d"
      - key: CORS_ORIGIN
        value: "*"
      - key: CLOUDINARY_CLOUD_NAME
        value: "durchmyhd"
      - key: CLOUDINARY_API_KEY
        value: "385354589753143"
      - key: CLOUDINARY_API_SECRET
        value: "F8THR1gRfU7AHKXX77c8MHzHG1c"
    healthCheckPath: /api/health
    autoDeploy: true
